deckhouse/deckhouse-cli

- internal/mirror/cmd/push/push.go
- internal/mirror/layouts/pull.go
Fixed Standard edition mirroring by not requiring Trivy database images to exist in registry as SE has no builtin vulnerability scanner
> Fix SE edition mirroring

- .github/workflows/release.yaml
- Taskfile.yml
1) Added tests in taskfile
2) Added tests execution when creating a PR to the main branch.
> Run go tests when PR in main branch

- d8-install.sh
Updated `d8-install.sh` to use sha256sum instead of shasum and download binaries from deckhouse website instead of github releases
> chore: update install script

- internal/mirror/cmd/vulndb/pull/pull.go
- internal/mirror/cmd/vulndb/push/push.go
- pkg/libmirror/layouts/layouts.go
- pkg/libmirror/layouts/pull.go
- pkg/libmirror/layouts/pull_test.go
- pkg/libmirror/operations/push.go
- testing/e2e/mirror/mirror_e2e_test.go
Included a new `security/trivy-checks:0` image into mirror
> feature: mirror of security/trivy-checks:0 image

- go.mod
- go.sum
- internal/virtualization/README.md
- internal/virtualization/cmd/lifecycle/evict.go
- internal/virtualization/cmd/lifecycle/lifecycle.go
- internal/virtualization/cmd/lifecycle/migrate.go
- internal/virtualization/cmd/lifecycle/restart.go
- internal/virtualization/cmd/lifecycle/start.go
- internal/virtualization/cmd/lifecycle/stop.go
- internal/virtualization/cmd/lifecycle/vmop/vmop.go
- internal/virtualization/virtualization.go
Add evict subcommand for d8 virtualization
> feat(virtualization): add evict subcommand

- internal/backup/cmd/backup.go
- internal/backup/cmd/cluster-config/cluster_config.go
- internal/backup/cmd/etcd/etcd.go
- internal/backup/cmd/etcd/flags.go
- internal/backup/cmd/flags.go
- internal/backup/configs/configmaps/backup.go
- internal/backup/configs/crds/custom_resources.go
- internal/backup/configs/roles/cluster_roles.go
- internal/backup/configs/secrets/backup.go
- internal/backup/configs/storageclasses/storage_classes.go
- internal/backup/configs/tarball/backup.go
- internal/backup/configs/whitelist/whitelist.go
- internal/backup/configs/whitelist/whitelist.yml
- internal/backup/configs/whitelist/whitelist_test.go
- internal/backup/utilk8s/clientset.go
Added a `backup cluster-config` subcommand that saves a set of predefined resources and all custom resources which CRD's are labeled as `backup.deckhouse.io/cluster-config: "true"`.
> Backup of cluster configuration

- pkg/libmirror/util/errorutil/errors.go
Authored by @unreturned in https://github.com/deckhouse/deckhouse-cli/pull/55
Handle error for trivy-bdu
```
Nov 14 21:27:42.714 INFO  ║ Mirroring kovalkov-quay.ru-central1.internal/user/dkp/security/trivy-bdu
Nov 14 21:27:42.715 INFO  ║ [1 / 1] Pushing image kovalkov-quay.ru-central1.internal/user/dkp/security/trivy-bdu:1
Nov 14 21:28:44.409 WARN  ║ Push image: "": task failed to many times, last error: Write kovalkov-quay.ru-central1.internal/user/dkp/security/trivy-bdu:1 to registry: PUT https://kovalkov-quay.ru-central1.internal/v2/user/dkp/security/trivy-bdu/manifests/1: MANIFEST_INVALID: manifest invalid; map[message:failed to parse manifest: manifest data does not match schema: 'application/octet-stream' is not one of ['application/vnd.oci.image.config.v1+json', …
```
> mirror: update trivy mimetypes error text for trivy-checks

- .github/workflows/release.yaml
- Taskfile.yml
Made all build Cgo-less, added a build for `linux/arm64` target
> feat: Avoid Cgo build for linux/arm64

- internal/virtualization/cmd/lifecycle/lifecycle.go
- internal/virtualization/cmd/lifecycle/vmop/vmop.go
I would like -w to wait for the whole operation to finish, i.e. stop/start/restart.
And if a command is started without a flag, it should wait for the Failed or InProgress phase and exit with that.
For some special cases when you need to create a vmop and exit immediately, you can make a special flag, for example, --create-only.
> refactor(virtualization): lifecycle wait flag behavior

- internal/mirror/cmd/modules/modules.go
- internal/mirror/cmd/modules/pull/pull.go
- internal/mirror/cmd/modules/push/push.go
- internal/mirror/cmd/pull/pull.go
- internal/mirror/cmd/push/push.go
- internal/mirror/cmd/vulndb/pull/pull.go
- internal/mirror/cmd/vulndb/push/push.go
- internal/mirror/cmd/vulndb/vulndb.go
Fixed `--insecure` and `--tls-skip-verify` flags ignored during vunerability database mirroring. Also cleaned up mirror flags in general by removing some kubectl flags that were added by mistake.
> mirror: Fix vulnerability database mirroring over HTTP

- go.mod
- go.sum
- internal/virtualization/cmd/console/console.go
- internal/virtualization/cmd/lifecycle/vmop/vmop.go
- internal/virtualization/cmd/vnc/vnc.go
- internal/virtualization/util/console.go
Expected console operation:
- Reconnect every second if connection is lost (network, reboot, VM shutdown)
- If someone else is connected or VM is not found, do not try to reconnect.
> feat(virtualization): serial/vnc reconnect

- d8-install.sh
Right now, running `d8-install.sh` fails with the error `Unexpected error during install: install: cannot stat '/tmp/d8-installer-XXXXX/linux-amd64/d8': No such file or directory`. 
Since #68, the build is stored in /bin/ directory, and this change is reflected in Taskfile, but not in `d8-install.sh`.
> fix: add bin directory to install path

- internal/mirror/cmd/pull/pull.go
- pkg/libmirror/bundle/bundle.go
- pkg/libmirror/images/digests.go
- pkg/libmirror/layouts/indexes.go
- pkg/libmirror/layouts/indexes_test.go
- pkg/libmirror/layouts/layouts.go
- pkg/libmirror/layouts/layouts_test.go
This PR ensures that tar bundles that contain exactly the same set of images will have their checksums equal, which was not the case before
> mirror: Reproducible bundles

- go.mod
- internal/platform/cmd/edit/editconfig/editconfig.go
- internal/platform/cmd/module/disable/disable.go
- internal/platform/cmd/module/enable/enable.go
- internal/platform/cmd/module/flags/flags.go
- internal/platform/cmd/module/list/list.go
- internal/platform/cmd/module/module.go
- internal/platform/cmd/module/operatemodule/optionsmodule.go
- internal/platform/cmd/module/operatemodule/switchmodule.go
- internal/platform/cmd/module/operatemodule/switchmodule_test.go
- internal/platform/cmd/module/snapshots/snapshots.go
- internal/platform/cmd/module/v1alpha1/v1alpha1.go
- internal/platform/cmd/module/values/values.go
- internal/platform/cmd/platform.go
This pr add platform module options to d8 like enable ,disable, lists, snapshots and values.
e.g. 
```
Usage:
d8 platform module [command]
Available Commands:
disable     Disable module.
enable      Enable module.
list        List enabled modules.
snapshots   Dump shapshots.
values      Dump values.
```
> [d8] Add d8 module options

- pkg/libmirror/bundle/validation.go
Skip existence validation for platform release channels as they may not be in the platform package
> mirror: Ignore empty release-channels layout

- go.mod
- go.sum
github.com/containers/buildah: v1.37.4 -> v1.37.6
github.com/hashicorp/go-slug: v0.11.1 -> v0.16.3
> chore: bump some dependencies to fix high severity CVE's

- internal/platform/cmd/collect-debug-info/collect-debug-info.go
- internal/platform/cmd/collect-debug-info/debugTar/debugTar.go
- internal/platform/cmd/module/operatemodule/optionsmodule.go
- internal/platform/cmd/operatepod/operatepod.go
- internal/platform/cmd/platform.go
This pr add d8 platform collect-debug-info option to save output debug info to tar.gz archive.
e.g.
```
d8 p collect-debug-info --help
Collect debug info from Deckhouse Kubernetes Platform.
© Flant JSC 2025
Usage:
d8 platform collect-debug-info [flags]
Flags:
-h, --help   help for collect-debug-info
Global Flags:
-k, --kubeconfig string   KubeConfig of the cluster. (default is $KUBECONFIG when it is set, $HOME/.kube/config otherwise) (default "/root/.kube/config")
```
> [d8] Add d8 collect-debug-info

- internal/platform/cmd/collect-debug-info/debugTar/debugTar.go
- internal/platform/cmd/module/enable/enable.go
- internal/platform/cmd/module/module.go
- internal/platform/cmd/module/snapshots/snapshots.go
- internal/platform/cmd/module/values/values.go
- internal/platform/cmd/operatepod/operatepod.go
- internal/platform/cmd/platform.go
- internal/platform/cmd/queue/flags/flags.go
- internal/platform/cmd/queue/flags/validation.go
- internal/platform/cmd/queue/list/flags.go
- internal/platform/cmd/queue/list/list.go
- internal/platform/cmd/queue/mainqueue/mainqueue.go
- internal/platform/cmd/queue/operatequeue/operatequeue.go
- internal/platform/cmd/queue/queue.go
This pr add d8 platform queue option to dump all and main queue tasks from Deckhouse Kubernetes Platform.
e.g.
```
d8 p queue --help
Dump queues from Deckhouse Kubernetes Platform.
© Flant JSC 2025
Usage:
d8 platform queue [command]
Available Commands:
list        Dump all queues.
main        Dump main queue.
Flags:
-h, --help   help for queue
Global Flags:
-k, --kubeconfig string   KubeConfig of the cluster. (default is $KUBECONFIG when it is set, $HOME/.kube/config otherwise) (default "/root/.kube/config")
Use "d8 platform queue [command] --help" for more information about a command.
```
> [d8] Add d8 platform queue option

- internal/backup/cmd/backup.go
- internal/backup/cmd/loki/flags.go
- internal/backup/cmd/loki/loki.go
- internal/utilk8s/operatepod.go
This pr add d8 backup loki option to dump all logs from Loki api endpoint or in given range timestamps.
e.g.
```
d8 backup loki --help
Dump Loki logs.
This command dump all logs from Loki api or in given range timestamps in DKP.
© Flant JSC 2025
Usage:
d8 backup loki [flags]
Flags:
--end string     Set end timestamp range to dump logs from Loki. (Default get max end timestamp from Loki, ex. "2025-01-14 15:04:05".)
-h, --help           help for loki
--limit string   Limit max string to output per queue from Loki. (Default 5000 max limit strings per queue.)
--start string   Set start timestamp range to dump logs from Loki. (Default get max start timestamp from Loki, ex. "2025-01-12 15:04:05".)
Global Flags:
-k, --kubeconfig string   KubeConfig of the cluster. (default is $KUBECONFIG when it …
```
> [d8] Add d8 backup loki option

- cmd/helpjson.go
- internal/platform/cmd/platform.go
This pr allow use hidden option 'help-json' to get all d8 command options and their flags in json format .
output info is
```
name
description
version
aliases
flags
subcommands
```
ex.
```
{
"name": "d8",
"description": "d8 controls the Deckhouse Kubernetes Platform",
"version": "v0.10.5-17-g1cdbbfb",
"aliases": null,
"flags": {
"help": {
"description": "help for d8",
"shorthand": "h"
},
"version": {
"description": "version for d8",
"shorthand": "v"
}
},
"subcommands": [
{
"name": "backup",
"description": "Backup various parts of Deckhouse Kubernetes Platform",
"aliases": null,
"flags": {
"kubeconfig": {
"description": "KubeConfig of the cluster. (default is $KUBECONFIG when it is set, $HOME/.kube/config otherwise)",
"shorthand": "k"
}
},
"subcommands": [
{
"name": "cluster-config …
```
> [d8] Fetch all d8 command options and flags into json format output.

- internal/mirror/cmd/pull/pull.go
- internal/mirror/cmd/push/push.go
- internal/mirror/operations/pull_modules.go
- pkg/libmirror/validation/registry_access.go
- pkg/libmirror/validation/registry_access_test.go
Split single registry accessibility check into 3 separate checks, one per each package type:  platform, security and modules
> mirror: validate source registry availability more granularly

- internal/backup/cmd/cluster-config/cluster_config.go
- internal/backup/cmd/etcd/etcd.go
- internal/backup/cmd/flags.go
- internal/backup/cmd/loki/loki.go
- internal/platform/cmd/collect-debug-info/collect-debug-info.go
- internal/platform/cmd/edit/editconfig/editconfig.go
- internal/platform/cmd/module/disable/disable.go
- internal/platform/cmd/module/enable/enable.go
- internal/platform/cmd/module/list/list.go
- internal/platform/cmd/module/snapshots/snapshots.go
- internal/platform/cmd/module/values/values.go
- internal/platform/cmd/queue/list/list.go
- internal/platform/cmd/queue/mainqueue/mainqueue.go
- internal/platform/flags/flags.go
- internal/utilk8s/clientset.go
Added `--context` flag alongside `--kubeconfig` similar to `kubectl` to allow users to select specific kubernetes context from kubeconfig instead of default.
Closes https://github.com/deckhouse/deckhouse-cli/issues/110
> utilk8s: support default context overrides

- internal/platform/cmd/module/disable/disable.go
- internal/platform/cmd/module/enable/enable.go
- internal/platform/cmd/module/values/values.go
this pr allow to avoid panic if module was not provided in options:
> module enable
> module disable
> module values
ex.
```
d8 p module enable
Error: this command requires exactly 1 argument: module name
```
> [platform] Avoid panic argument if module name was not provided

- internal/system/cmd/system.go
Our docs mention `d8 platform` a lot of times and should be updated to `d8 system` in the future. Until then, alias `d8 p/platform` commands to `d8 system` for backwards compatibility with existing docs.
> [system] Add aliases "p" and "platform" to "d8 system" commands

- internal/tools/farconverter/cmd/far-convert.go
- internal/tools/gostsum/cmd/flags.go
- internal/tools/gostsum/cmd/gostsum.go
- internal/tools/gostsum/gostsum.go
- internal/tools/gostsum/gostsum_test.go
Added a gostsums-like tool to calculate streebog 256 and 512-bit variants under `d8 tools gostsum`
```
~ # d8 tools
Various useful tools for operating in The Deckhouse Ecosystem.
© Flant JSC 2025
Usage:
d8 tools [command]
Aliases:
tools, t
Available Commands:
far-convert Converts files with Falco rules to FalcoAuditRules CRD format
gostsum     Calculate Streebog checksum of the data according to the RFC 6986 (GOST R 34.11-2012) specifications
Flags:
-h, --help   help for tools
Use "d8 tools [command] --help" for more information about a command.
```
---
```
~ # d8 tools gostsum
Calculate Streebog checksum of the data according to the RFC 6986 (GOST R 34.11-2012) specifications.
Data for checksumming is provided as a list of filepaths in the command-line arguments.
If no filepaths are …
```
> [tools] gostsum
